# Generated by Django 3.2.5 on 2021-08-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_amount_orders_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_amount',
        ),
    ]
